// src/common/components/navbar/NavBarMusicControl.vue
<template>
	<ion-buttons slot="primary" class="navbar-music-control">
		<NavBarVolumeSlider></NavBarVolumeSlider>
		<div>
			<ion-button @click="toggleSetting('isRepeat')" v-toggleClass="{ 'navbar-music-control--active': isRepeat }">
				<ion-icon slot="icon-only" name="repeat"></ion-icon>
			</ion-button>
		</div>
		<ion-button @click="toggleSetting('isShuffle')" v-toggleClass="{ 'navbar-music-control--active': isShuffle }">
			<ion-icon slot="icon-only" name="shuffle"></ion-icon>
		</ion-button>
		<ion-button href="https://github.com/zwacky/game-music-player" @click="trackClickout()" target="_blank" rel="noopener" class="navbar-music-control--active" title="Go to GitHub project">
			<ion-icon slot="icon-only" name="logo-github"></ion-icon>
		</ion-button>
	</ion-buttons>
</template>

<script lang="ts">
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { Getter, namespace, Mutation } from 'vuex-class';
import { PlayerStore } from '@/common/stores/player.store';
import NavBarVolumeSlider from './NavBarVolumeSlider.vue';

const Player = namespace('player');
const Settings = namespace('settings');

@Component({
	components: { NavBarVolumeSlider },
})
export default class NavBarMusicControl extends Vue {
	@Player.Getter filteredTracks;
	@Settings.Getter isRepeat;
	@Settings.Getter isShuffle;

	@Settings.Action toggleSetting;

	created() {
		// setInterval(() => {
		// 	console.log('xxx', this.isRepeat);
		// }, 1000);
	}

	trackClickout() {
		console.log('trackClickout');
	}
	
}
</script>

<style lang="scss">
.navbar-music-control {
	ion-button {
		opacity: 0.3;
		transition: opacity 0.25s ease-in-out;
		color: black;
	}

	// ion-button {
	// 	opacity: 0.3;
	// 	transition: opacity 0.25s ease-in-out;
	// 	color: black;
	// }

	&--active {
		// --ion-opacity: 1 !important;
		opacity: 1 !important;
	}
}
</style>

// src/pages/home/nav/navbar-music-control.component.ts
import { Component } from '@angular/core';

import { Store } from '@ngrx/store';
import { Observable } from "rxjs";
import { AppState } from "../../../app/app.state";
import { PlayerActions } from "../../../common/player/player.actions";
import { isShuffle, isRepeat } from "../../../common/player/player.selectors";


@Component({
	selector: 'navbar-music-control',
	template: `
		<ion-buttons start end class="navbar-music-control">
			<a href="https://github.com/zwacky/game-music-player" target="_blank" ion-button icon-only class="navbar-music-control--active" title="Go to GitHub project">
				<ion-icon name="logo-github"></ion-icon>
			</a>
			<button ion-button icon-only (click)="toggleSetting('isRepeat')" [ngClass]="{'navbar-music-control--active': (isRepeat$ | async)}">
				<ion-icon name="repeat"></ion-icon>
			</button>
			<button ion-button icon-only (click)="toggleSetting('isShuffle')" [ngClass]="{'navbar-music-control--active': (isShuffle$ | async)}">
				<ion-icon name="shuffle"></ion-icon>
			</button>
		</ion-buttons>
	`
})
export class NavbarMusicControl {

	isShuffle$: Observable<boolean>;
	isRepeat$: Observable<boolean>;

	constructor(
		private store: Store<AppState>,
		private playerActions: PlayerActions
	) {
		this.isShuffle$ = this.store.select(isShuffle);
		this.isRepeat$ = this.store.select(isRepeat);
	}

	toggleSetting(settingKey: string) {
		this.store.dispatch(this.playerActions.toggleSetting(settingKey));
	}

}
